blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/fernkit/fern/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/fernkit/fern/blob/master/README.md
    about: Check out the official documentation